import {
  Github,
  Linkedin,
  Mail,
  Twitter,
  Instagram,
  Youtube,
  Facebook,
  Globe,
  Twitch,
  FileCode,
  Codepen,
  Gitlab,
  MessagesSquare,
  Newspaper,
  Paintbrush,
  Palette,
  Hash,
  BookOpen,
  Rss,
  Share,
  Link as LinkIcon,
  type LucideIcon,
} from "lucide-react";

export const socialIconMap: Record<string, LucideIcon> = {
  github: Github,
  gitlab: Gitlab,
  codepen: Codepen,
  stackoverflow: Hash,
  linkedin: Linkedin,
  portfolio: FileCode,
  website: Globe,
  blog: Newspaper,
  mail: Mail,
  discord: MessagesSquare,
  rss: Rss,
  twitter: Twitter,
  instagram: Instagram,
  youtube: Youtube,
  facebook: Facebook,
  twitch: Twitch,
  behance: Paintbrush,
  dribbble: Palette,
  medium: BookOpen,
  link: LinkIcon,
  share: Share,
};
